### ISSUE TITLE
Verification Code Box is Blank

### ISSUE THREAD

**Issue by SickSick6** [davidjeddy/pieces-compendium-v2#5]
The box that displays the Verification Code captcha on the Contact page is blank preventing the ability to send an email from the site

**Comment by davidjeddy** [comment]
FIXED: https://pieces-compendium.com/site/contact

<img width="1013" alt="screen shot 2018-10-12 at 5 35 09 pm" src="https://user-images.githubusercontent.com/6232455/46895159-39a54d80-ce45-11e8-85c2-42bd4631eb40.png">
